name: ros-model-cloud

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ros-model-cloud
    - name: Build docker containers
      run: |
        pushd ros-model-cloud
        ./setup_helper.sh
    - name: Start the containers
      run: |
        pushd ros-model-cloud
        docker-compose up & docker-compose down
